import 'dart:convert';

import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:damage_calc/data/fling_powers.dart';
import 'package:damage_calc/data/itemdex.dart';

/// lib/data/fling_powers.dart is generated by tools/gen_fling_powers.py
/// from Showdown's item data. These pin its shape so a regeneration
/// against a changed upstream can't quietly drop half the roster.
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  test('every entry is a held item and has a real power', () async {
    final dex = await loadItemdex();
    expect(kFlingPowers.length, greaterThan(250));
    for (final e in kFlingPowers.entries) {
      expect(dex[e.key], isNotNull, reason: '${e.key} missing from items.json');
      expect(dex[e.key]!.held, isTrue, reason: '${e.key} is not a held item');
      expect(e.value, greaterThan(0), reason: e.key);
    }
  });

  test('every Champions-legal item is flingable except the gem', () async {
    final raw = json.decode(
        await rootBundle.loadString('assets/champions_items.json'));
    final legal = (raw['items'] as List).cast<String>();
    final missing = [for (final k in legal) if (!kFlingPowers.containsKey(k)) k];
    expect(missing, ['normal-gem']);
  });
}
