name: damage_calc
description: Battle damage calculator
publish_to: 'none'
version: 1.6.0+111

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  screenshot: ^3.0.0
  path_provider: ^2.1.0
  shared_preferences: ^2.5.4
  flutter_typeahead: ^5.2.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Fallback.ttf
    - family: MPLUSRounded1c
      fonts:
        - asset: assets/fonts/MPLUSRounded1c-Regular.ttf

  assets:
    - assets/
    - assets/fonts/
    - assets/pokemon/
    - assets/moves/
