name: damage_calc
description: Battle damage calculator
publish_to: 'none'
version: 0.3.1+16

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  screenshot: ^3.0.0
  path_provider: ^2.1.0
  shared_preferences: ^2.5.4
  flutter_typeahead: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: Jua
      fonts:
        - asset: assets/fonts/Jua-Regular.ttf
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Fallback.ttf
    - family: MPLUSRounded1c
      fonts:
        - asset: assets/fonts/MPLUSRounded1c-Regular.ttf

  assets:
    - assets/
    - assets/fonts/
    - assets/pokemon/
    - assets/moves/
