#!/usr/bin/env python3
"""Generate lib/calc/fling_powers.dart from Pokémon Showdown's item data.

Fling's base power is a per-item property (Iron Ball 130, Rocky Helmet
60, Choice Scarf 10, …) and items without a `fling` entry — Mega Stones,
Z-Crystals, gems, orbs of the Weather trio — make the move fail. The
table used to be hand-written and was wrong for 80 of our held items
(Choice Scarf shipped as 80, user report 2026-09-12), so it is now
generated from `data/items.ts` in smogon/pokemon-showdown, matched to
assets/items.json by English name.

Usage:
    python3 tools/gen_fling_powers.py            # fetch items.ts from GitHub
    python3 tools/gen_fling_powers.py --src X.ts # use a local copy

Output: lib/calc/fling_powers.dart — a const map items.json slug → power
for every held item Showdown lists as flingable. Held items with no
entry are unflingable; the move transform treats them as power 0.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import time
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ITEMS_PATH = REPO / "assets" / "items.json"
OUT_PATH = REPO / "lib" / "calc" / "fling_powers.dart"
URL = "https://raw.githubusercontent.com/smogon/pokemon-showdown/master/data/items.ts"
MIN_PLAUSIBLE = 200


def norm(s: str) -> str:
    return s.replace("\u2019", "'").strip().lower()


def ident(s: str) -> str:
    """Showdown-style id: lowercase alphanumerics only (our slug minus hyphens)."""
    return re.sub(r"[^a-z0-9]", "", s.lower())


def parse_showdown(src: str) -> dict[str, int]:
    """Showdown id -> fling base power, including the implicit classes the
    sim assigns in sim/dex-items.ts (berries 10, plates 90, drives 70,
    Mega Stones 80, memories 50). Items with no power are unflingable."""
    out: dict[str, int] = {}
    for key, body in re.findall(r"\n\t(\w+): \{\n(.*?)\n\t\},", src, flags=re.S):
        f = re.search(r"fling: \{\s*basePower: (\d+)", body)
        power = int(f.group(1)) if f else None
        if "isBerry: true" in body:
            power = 10
        if key.endswith("plate"):
            power = 90
        if re.search(r"^\t\tonDrive:", body, flags=re.M):
            power = 70
        if re.search(r"^\t\tmegaStone:", body, flags=re.M):
            power = 80
        if re.search(r"^\t\tonMemory:", body, flags=re.M):
            power = 50
        if power is not None:
            out[key] = power
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", help="local copy of pokemon-showdown data/items.ts")
    args = ap.parse_args()
    if args.src:
        src = Path(args.src).read_text(encoding="utf-8")
    else:
        print(f"fetching {URL} …")
        req = urllib.request.Request(URL, headers={"User-Agent": "damage-calc/1"})
        with urllib.request.urlopen(req, timeout=30) as r:
            src = r.read().decode("utf-8")
    ref = parse_showdown(src)
    print(f"Showdown flingable items: {len(ref)}")
    if len(ref) < MIN_PLAUSIBLE:
        print(f"ABORT: only {len(ref)} entries (< {MIN_PLAUSIBLE}) — format changed?")
        return 1

    items = json.loads(ITEMS_PATH.read_text(encoding="utf-8"))
    table: dict[str, int] = {}
    unflingable: list[str] = []
    for it in items:
        if not it.get("held"):
            continue
        slug = it["name"]
        power = ref.get(ident(slug))
        if power is None and it.get("nameEn"):
            power = ref.get(ident(it["nameEn"]))
        # Champions' own Mega Stones (Absolite Z, Baxcalibrite, …) don't
        # exist in Showdown; the game files name every Mega Stone
        # "…나이트" / "…나이트Z", and Mega Stones fling for 80.
        if power is None and re.search(r"나이트Z?$", it.get("nameKo", "")):
            power = 80
        if power is None:
            unflingable.append(slug)
        else:
            table[slug] = power
    print(f"held items with a fling power: {len(table)}; unflingable: {len(unflingable)}")
    print("unflingable:", ", ".join(sorted(unflingable)))

    by_power: dict[int, list[str]] = {}
    for k, v in table.items():
        by_power.setdefault(v, []).append(k)
    lines = [
        "// GENERATED by tools/gen_fling_powers.py — do not edit by hand.",
        f"// Source: smogon/pokemon-showdown data/items.ts, {time.strftime('%Y-%m-%d')}.",
        "//",
        "// Fling base power per held item (items.json slug). A held item",
        "// missing from this map is unflingable (Mega Stones, Z-Crystals,",
        "// gems, …): the move fails, which the transform models as power 0.",
        "",
        "const Map<String, int> kFlingPowers = {",
    ]
    for p in sorted(by_power, reverse=True):
        lines.append(f"  // {p}")
        for k in sorted(by_power[p]):
            lines.append(f"  '{k}': {p},")
    lines.append("};")
    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT_PATH} ({len(table)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
